import { Content } from './content';

export const CONTENT = {
  one: new Content(
    'Welcome to the troll house!',
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tristique elementum porttitor. Suspendisse vitae tortor luctus, malesuada nisl id, maximus neque. Aliquam vitae ultricies mi. Nulla interdum id nibh sed sollicitudin. Proin ut diam sit amet urna vulputate lobortis. In varius ante vitae justo tempus fermentum sit amet sit amet dui. In finibus, risus a laoreet blandit, ex lorem cursus leo, vitae efficitur metus velit et orci. Vestibulum aliquam auctor quam, at sagittis ipsum bibendum quis. Cras pharetra purus odio, a tristique tellus ultrices ac. Praesent dapibus odio dolor. Morbi consectetur sapien vitae lacus accumsan, a vehicula lacus molestie. Fusce fermentum cursus odio eget vulputate. Fusce a sem diam. Nullam eu tellus vitae sapien ultricies vestibulum quis vitae orci. In rutrum lectus eu sem venenatis, nec tempor metus vestibulum. Duis vitae tempus neque. Nullam sit amet viverra quam. Vivamus porttitor urna lectus, et pellentesque ex elementum nec. Morbi semper finibus ante nec mollis. Pellentesque vel odio turpis. Sed mollis ultricies sollicitudin. Nullam ac turpis ut ligula imperdiet tempus id at eros. Mauris interdum euismod ipsum, sed aliquet est.",
    ['hourly']
  ),
  two: new Content(
    'Page one',
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tristique elementum porttitor. Suspendisse vitae tortor luctus, malesuada nisl id, maximus neque. Aliquam vitae ultricies mi. Nulla interdum id nibh sed sollicitudin. Proin ut diam sit amet urna vulputate lobortis. In varius ante vitae justo tempus fermentum sit amet sit amet dui. In finibus, risus a laoreet blandit, ex lorem cursus leo, vitae efficitur metus velit et orci. Vestibulum aliquam auctor quam, at sagittis ipsum bibendum quis. Cras pharetra purus odio, a tristique tellus ultrices ac. Praesent dapibus odio dolor. Morbi consectetur sapien vitae lacus accumsan, a vehicula lacus molestie. Fusce fermentum cursus odio eget vulputate. Fusce a sem diam. Nullam eu tellus vitae sapien ultricies vestibulum quis vitae orci. In rutrum lectus eu sem venenatis, nec tempor metus vestibulum. Duis vitae tempus neque. Nullam sit amet viverra quam. Vivamus porttitor urna lectus, et pellentesque ex elementum nec. Morbi semper finibus ante nec mollis. Pellentesque vel odio turpis. Sed mollis ultricies sollicitudin. Nullam ac turpis ut ligula imperdiet tempus id at eros. Mauris interdum euismod ipsum, sed aliquet est.",
    ['daily']
  ),
  three: new Content(
    'Page two',
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tristique elementum porttitor. Suspendisse vitae tortor luctus, malesuada nisl id, maximus neque. Aliquam vitae ultricies mi. Nulla interdum id nibh sed sollicitudin. Proin ut diam sit amet urna vulputate lobortis. In varius ante vitae justo tempus fermentum sit amet sit amet dui. In finibus, risus a laoreet blandit, ex lorem cursus leo, vitae efficitur metus velit et orci. Vestibulum aliquam auctor quam, at sagittis ipsum bibendum quis. Cras pharetra purus odio, a tristique tellus ultrices ac. Praesent dapibus odio dolor. Morbi consectetur sapien vitae lacus accumsan, a vehicula lacus molestie. Fusce fermentum cursus odio eget vulputate. Fusce a sem diam. Nullam eu tellus vitae sapien ultricies vestibulum quis vitae orci. In rutrum lectus eu sem venenatis, nec tempor metus vestibulum. Duis vitae tempus neque. Nullam sit amet viverra quam. Vivamus porttitor urna lectus, et pellentesque ex elementum nec. Morbi semper finibus ante nec mollis. Pellentesque vel odio turpis. Sed mollis ultricies sollicitudin. Nullam ac turpis ut ligula imperdiet tempus id at eros. Mauris interdum euismod ipsum, sed aliquet est.",
    ['monthly']
  ),
  four: new Content(
    'Page three',
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tristique elementum porttitor. Suspendisse vitae tortor luctus, malesuada nisl id, maximus neque. Aliquam vitae ultricies mi. Nulla interdum id nibh sed sollicitudin. Proin ut diam sit amet urna vulputate lobortis. In varius ante vitae justo tempus fermentum sit amet sit amet dui. In finibus, risus a laoreet blandit, ex lorem cursus leo, vitae efficitur metus velit et orci. Vestibulum aliquam auctor quam, at sagittis ipsum bibendum quis. Cras pharetra purus odio, a tristique tellus ultrices ac. Praesent dapibus odio dolor. Morbi consectetur sapien vitae lacus accumsan, a vehicula lacus molestie. Fusce fermentum cursus odio eget vulputate. Fusce a sem diam. Nullam eu tellus vitae sapien ultricies vestibulum quis vitae orci. In rutrum lectus eu sem venenatis, nec tempor metus vestibulum. Duis vitae tempus neque. Nullam sit amet viverra quam. Vivamus porttitor urna lectus, et pellentesque ex elementum nec. Morbi semper finibus ante nec mollis. Pellentesque vel odio turpis. Sed mollis ultricies sollicitudin. Nullam ac turpis ut ligula imperdiet tempus id at eros. Mauris interdum euismod ipsum, sed aliquet est.",
    ['yearly']
  ),
  five: new Content(
    'Page four',
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tristique elementum porttitor. Suspendisse vitae tortor luctus, malesuada nisl id, maximus neque. Aliquam vitae ultricies mi. Nulla interdum id nibh sed sollicitudin. Proin ut diam sit amet urna vulputate lobortis. In varius ante vitae justo tempus fermentum sit amet sit amet dui. In finibus, risus a laoreet blandit, ex lorem cursus leo, vitae efficitur metus velit et orci. Vestibulum aliquam auctor quam, at sagittis ipsum bibendum quis. Cras pharetra purus odio, a tristique tellus ultrices ac. Praesent dapibus odio dolor. Morbi consectetur sapien vitae lacus accumsan, a vehicula lacus molestie. Fusce fermentum cursus odio eget vulputate. Fusce a sem diam. Nullam eu tellus vitae sapien ultricies vestibulum quis vitae orci. In rutrum lectus eu sem venenatis, nec tempor metus vestibulum. Duis vitae tempus neque. Nullam sit amet viverra quam. Vivamus porttitor urna lectus, et pellentesque ex elementum nec. Morbi semper finibus ante nec mollis. Pellentesque vel odio turpis. Sed mollis ultricies sollicitudin. Nullam ac turpis ut ligula imperdiet tempus id at eros. Mauris interdum euismod ipsum, sed aliquet est.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tristique elementum porttitor. Suspendisse vitae tortor luctus, malesuada nisl id, maximus neque. Aliquam vitae ultricies mi. Nulla interdum id nibh sed sollicitudin. Proin ut diam sit amet urna vulputate lobortis. In varius ante vitae justo tempus fermentum sit amet sit amet dui. In finibus, risus a laoreet blandit, ex lorem cursus leo, vitae efficitur metus velit et orci. Vestibulum aliquam auctor quam, at sagittis ipsum bibendum quis. Cras pharetra purus odio, a tristique tellus ultrices ac. Praesent dapibus odio dolor. Morbi consectetur sapien vitae lacus accumsan, a vehicula lacus molestie. Fusce fermentum cursus odio eget vulputate. Fusce a sem diam. Nullam eu tellus vitae sapien ultricies vestibulum quis vitae orci. In rutrum lectus eu sem venenatis, nec tempor metus vestibulum. Duis vitae tempus neque. Nullam sit amet viverra quam. Vivamus porttitor urna lectus, et pellentesque ex elementum nec. Morbi semper finibus ante nec mollis. Pellentesque vel odio turpis. Sed mollis ultricies sollicitudin. Nullam ac turpis ut ligula imperdiet tempus id at eros. Mauris interdum euismod ipsum, sed aliquet est.",
    ['author_ten_gop', 'author_novostimsk']
  )
}
